package activity.client.gui.custom;
import com.google.gson.*;
import java.nio.file.*;
import activity.client.gui.custom.api.modules.settings.Setting;
import activity.client.gui.custom.api.modules.settings.impl.*;
public final class VisualSettingsStore {
 private static boolean loaded,loading,dirty;private static long lastChange;
 public static void markDirty(){if(loading||!loaded)return;dirty=true;lastChange=System.nanoTime();}
 public static void tick(){if(dirty && System.nanoTime()-lastChange>=500000000L)save();}
 private static Path path(){return net.fabricmc.loader.api.FabricLoader.getInstance().getConfigDir().resolve("nc-visual.json");}
 private static Object[] modules(){var m=activity.client.gui.custom.api.modules.ModuleManager.get();return new Object[]{VisualMaterial.getInstance(),m.get(activity.client.gui.custom.api.modules.impl.Interface.ClickGui.class),m.get(activity.client.gui.custom.api.modules.impl.Utils.ClientSounds.class)};}
 public static boolean isLoading(){return loading;}
 public static void load(){if(loaded)return;loaded=true;loading=true;try{if(Files.exists(path())){JsonObject root=JsonParser.parseString(Files.readString(path())).getAsJsonObject();for(Object m:modules())for(var f:m.getClass().getFields()){String key=m.getClass().getSimpleName()+"."+f.getName();if(!root.has(key))continue;Object v=f.get(m);JsonElement j=root.get(key);if(v instanceof BooleanSetting a)a.setValue(j.getAsBoolean());else if(v instanceof SliderSetting a)a.setValue(j.getAsFloat());else if(v instanceof SelectSetting a)a.setSelected(j.getAsString());else if(v instanceof ColorSetting a)a.setColor(j.getAsInt());}if(root.has("pinnedThemes")){java.util.List<String> pins=new java.util.ArrayList<>();for(var pin:root.getAsJsonArray("pinnedThemes"))pins.add(pin.getAsString());activity.client.gui.custom.api.ui.theme.ThemePins.load(pins);}if(root.has("sidebar"))activity.client.gui.custom.api.ui.UI.customSidebarW=root.get("sidebar").getAsFloat();}var cfg=activity.client.config.ActivityConfigManager.getConfig();activity.client.gui.custom.api.ui.pin.PinManager.setPinnedNames(cfg.pinnedModules);activity.client.gui.custom.api.localization.LocalizationManager.setLanguage(cfg.language);activity.client.gui.custom.api.ui.theme.CustomThemeManager.init();var theme=activity.client.gui.custom.api.ui.theme.CustomThemeManager.getById(cfg.guiTheme);if(theme!=null)activity.client.gui.custom.api.ui.theme.ThemeManager.set(theme);else CustomRender.theme(activity.client.gui.theme.ThemePreset.fromId(cfg.guiTheme));}catch(Exception e){activity.client.ActivityClient.LOGGER.warn("Visual settings could not be loaded",e);}finally{loading=false;}}
 public static void save(){if(loading||!loaded)return;try{JsonObject root=new JsonObject();for(Object m:modules())for(var f:m.getClass().getFields()){Object v=f.get(m);String key=m.getClass().getSimpleName()+"."+f.getName();if(v instanceof BooleanSetting a)root.addProperty(key,a.getValue());else if(v instanceof SliderSetting a)root.addProperty(key,a.getFloat());else if(v instanceof SelectSetting a)root.addProperty(key,a.getSelected());else if(v instanceof ColorSetting a)root.addProperty(key,a.getColor());}JsonArray pins=new JsonArray();for(var pin:activity.client.gui.custom.api.ui.theme.ThemePins.ids())pins.add(pin);root.add("pinnedThemes",pins);root.addProperty("sidebar",activity.client.gui.custom.api.ui.UI.customSidebarW);Files.createDirectories(path().getParent());Path temp=path().resolveSibling("nc-visual.json.tmp");Files.writeString(temp,new GsonBuilder().setPrettyPrinting().create().toJson(root));try{Files.move(temp,path(),StandardCopyOption.REPLACE_EXISTING,StandardCopyOption.ATOMIC_MOVE);}catch(AtomicMoveNotSupportedException e){Files.move(temp,path(),StandardCopyOption.REPLACE_EXISTING);}dirty=false;}catch(Exception e){activity.client.ActivityClient.LOGGER.warn("Visual settings could not be saved",e);}}
}
